apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hookbridge.fullname" . }}-config
  labels:
    {{- include "hookbridge.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  MongoDb__DatabaseName: {{ .Values.config.mongodb.databaseName | quote }}
  Kafka__BootstrapServers: {{ .Values.config.kafka.bootstrapServers | quote }}
  Elastic__ElasticsearchUrl: {{ .Values.config.elastic.elasticsearchUrl | quote }}
  Elastic__Environment: {{ .Values.config.elastic.environment | quote }}
  ElasticApm__ServerUrl: {{ .Values.config.elasticApm.serverUrl | quote }}
  ElasticApm__Enabled: {{ .Values.config.elasticApm.enabled | quote }}
