apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hookbridge.fullname" . }}-secret
  labels:
    {{- include "hookbridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  MongoDb__ConnectionString: {{ .Values.config.mongodb.connectionString | quote }}
  Stripe__SecretKey: {{ .Values.secrets.stripe.secretKey | quote }}
  Stripe__WebhookSecret: {{ .Values.secrets.stripe.webhookSecret | quote }}
  Jwt__Secret: {{ .Values.secrets.jwt.secret | quote }}
