using HookBridge.AI.Worker;
using HookBridge.AI.Worker.Extensions;
using HookBridge.AI.Worker.Health;

var builder = Host.CreateApplicationBuilder(args);

builder.Services.AddAiOptions(builder.Configuration);
builder.Services.AddAiRecommendationApprovalServices(builder.Configuration);
builder.Services.AddAiSafeModeServices(builder.Configuration);
builder.Services.AddAiKafkaOptions(builder.Configuration);
builder.Services.AddDuplicateReplayDetectionOptions(builder.Configuration);
builder.Services.AddAutoRemediationRecommendationServices(builder.Configuration);
builder.Services.AddDeadLetterAiAnalysisServices(builder.Configuration);
builder.Services.AddAiAgentOrchestrationServices(builder.Configuration);
builder.Services.AddSecurityAgentServices(builder.Configuration);
builder.Services.AddTransformationAgentServices(builder.Configuration);
builder.Services.AddObservabilityAgentServices(builder.Configuration);
builder.Services.AddAiMongoOptions(builder.Configuration);
builder.Services.AddSingleton<AiWorkerHealthStatus>();
builder.Services.AddAiKernelServices();
builder.Services.AddAiPromptServices();
builder.Services.AddAiRetryRecommendationServices();
builder.Services.AddRetryAgentServices(builder.Configuration);
builder.Services.AddAiLogSummarizationServices();
builder.Services.AddPayloadSchemaDetectionServices();
builder.Services.AddJsonToDtoSuggestionServices();
builder.Services.AddFluentValidationRuleGenerationServices();
builder.Services.AddWebhookTransformationRecommendationServices();
builder.Services.AddEndpointHealthScoringServices();
builder.Services.AddCustomerEndpointRiskScoringServices();
builder.Services.AddWebhookFailureAnomalyDetectionServices();
builder.Services.AddAiSecurityAnalysisServices();
builder.Services.AddWebhookDuplicateReplayDetectionServices();
builder.Services.AddAiKafkaServices();
builder.Services.AddAiMongoServices();
builder.Services.AddHostedService<AiProcessingWorker>();
builder.Services.AddHostedService<PayloadSchemaDetectionWorker>();
builder.Services.AddHostedService<JsonToDtoSuggestionWorker>();
builder.Services.AddHostedService<FluentValidationRuleGenerationWorker>();
builder.Services.AddHostedService<WebhookTransformationRecommendationWorker>();
builder.Services.AddHostedService<CustomerEndpointRiskScoreWorker>();
builder.Services.AddHostedService<WebhookFailureAnomalyDetectionWorker>();
builder.Services.AddHostedService<AiAnomalyRecordPersistenceWorker>();
builder.Services.AddHostedService<AiSecurityAnalysisWorker>();
builder.Services.AddHostedService<WebhookDuplicateReplayDetectionWorker>();
builder.Services.AddHostedService<AiAgentOrchestrationWorker>();
builder.Services.AddHostedService<RetryAgentWorker>();
builder.Services.AddHostedService<SecurityAgentWorker>();
builder.Services.AddHostedService<TransformationAgentWorker>();
builder.Services.AddHostedService<ObservabilityAgentWorker>();
builder.Services.AddHostedService<AutoRemediationRecommendationWorker>();
builder.Services.AddHostedService<DeadLetterAiAnalysisWorker>();

var host = builder.Build();
host.Run();
